### ISSUE TITLE
ImportError: cannot import name 'FilterParams' from 'py_clob_client.client' 

### ISSUE THREAD

**Issue by L1nkus** [Polymarket/poly-market-maker#74]
./run-local.sh 
Running poly-market-maker...
Sourcing env variables from dot env file...
Traceback (most recent call last):
  File "/home/opc/.pyenv/versions/3.10.15/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/opc/.pyenv/versions/3.10.15/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/opc/poly-market-maker/poly_market_maker/__main__.py", line 2, in <module>
    from poly_market_maker.app import App
  File "/home/opc/poly-market-maker/poly_market_maker/app.py", line 5, in <module>
    from poly_market_maker.args import get_args
  File "/home/opc/poly-market-maker/poly_market_maker/args.py", line 3, in <module>
    from poly_market_maker.strategy import Strategy
  File "/home/opc/poly-market-maker/poly_market_maker/strategy.py", line 6, in <module>
    from poly_market_maker.price_feed import PriceFeed
  File "/home/opc/poly-market-maker/poly_market_maker/price_feed.py", line 4, in <module>
    from poly_market_maker.clob_api import ClobApi
  File "/home/opc/poly-market-maker/poly_market_maker/clob_api.py", line 4, in <module>
    from py_clob_client.client import ClobClient, ApiCreds, OrderArgs, FilterParams
ImportError: cannot import name 'FilterParams' from 'py_clob_client.client' (/home/opc/poly-market-maker/.venv/lib/python3.10/site-packages/py_clob_client/client.py)

**Comment by elanrosen** [comment]
Have the same issue as well. @L1nkus did you find a solution?

**Comment by corneliusroemer** [comment]
Yep, also getting this, e.g. in CI: https://github.com/corneliusroemer/poly-market-maker/actions/runs/12653053426/job/35257273738

**Comment by corneliusroemer** [comment]
Fixed by: https://github.com/Polymarket/poly-market-maker/pull/71 or alternatively  https://github.com/Polymarket/poly-market-maker/pull/73
